// TACO dataset class ID → display name
// These IDs match YOLOv8 output after fine-tuning on TACO.
// Used by classifier.py (backend) and display logic (frontend).

export const TACO_CATEGORIES: Record<number, string> = {
  0:  'Aluminium foil',
  1:  'Battery',
  2:  'Aluminium blister pack',
  3:  'Carded blister pack',
  4:  'Other plastic bottle',
  5:  'Clear plastic bottle',
  6:  'Glass bottle',
  7:  'Plastic bottle cap',
  8:  'Metal bottle cap',
  9:  'Broken glass',
  10: 'Food Can',
  11: 'Aerosol',
  12: 'Drink can',
  13: 'Toilet tube',
  14: 'Other carton',
  15: 'Egg carton',
  16: 'Drink carton',
  17: 'Corrugated carton',
  18: 'Meal carton',
  19: 'Pizza box',
  20: 'Paper cup',
  21: 'Disposable plastic cup',
  22: 'Foam cup',
  23: 'Glass cup',
  24: 'Other plastic cup',
  25: 'Food waste',
  26: 'Glass jar',
  27: 'Plastic jar',
  28: 'Plastic lid',
  29: 'Metal lid',
  30: 'Other plastic',
  31: 'Magazine paper',
  32: 'Tissues',
  33: 'Wrapping paper',
  34: 'Normal paper',
  35: 'Paper bag',
  36: 'Plastified paper bag',
  37: 'Plastic film',
  38: 'Six pack rings',
  39: 'Garbage bag',
  40: 'Other plastic wrapper',
  41: 'Single-use carrier bag',
  42: 'Polypropylene bag',
  43: 'Crisp packet',
  44: 'Spread tub',
  45: 'Tupperware',
  46: 'Disposable food container',
  47: 'Foam food container',
  48: 'Other plastic container',
  49: 'Plastic gloves',
  50: 'Plastic utensils',
  51: 'Pop tab',
  52: 'Rope',
  53: 'Shoe',
  54: 'Squeezable tube',
  55: 'Plastic straw',
  56: 'Paper straw',
  57: 'Styrofoam piece',
  58: 'Unlabeled litter',
  59: 'Cigarette',
};
